name: Snyk

on: 
  push:
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: scala-guild
      SKIP_NODE: true
      EXCLUDE: aws-parameterstore
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
